server:
  port: ${APPLICATION_PORT}

spring:
  application:
    name: Innowise-Intership-Payment-Service
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?authSource=admin
      auto-index-creation: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${REALM}
  liquibase:
    change-log: /db/changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
random:
  org:
    url: ${RANDOM_ORG_URL}