server:
  port: ${APPLICATION_PORT}

spring:
  application:
    name: Innowise-Intership-Payment-Service
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      authentication-database: admin
      auto-index-creation: false
  liquibase:
    change-log: /db/changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}
random:
  org:
    url: ${RANDOM_ORG_URL}